### ISSUE TITLE
COMPSs Running within Allocation

### ISSUE THREAD

**Issue by manuel-g-castro** [bsc-wdc/compss#12]
## Level
**MINOR**

## Component
**PYTHON BINDING** (I think)

## Environment
* COMPSs/3.3
* python/3.7.4
* Default environment at MareNostrum4

## Description
Failure to run `launch_compss` with a hello-world python COMPSs workflow within an allocated node using `salloc`.

## Minimal example to reproduce
1) Login in to MN4 and run
```
salloc -N1 -t 30:00 --qos debug
```
2) Once allocation is granted, 

```
module load python/3.7.4
module load COMPSs/3.3
launch_compss \
    --sc_cfg=mn.cfg \
    --master_node="$SLURMD_NODENAME" \
    --worker_nodes="" \
    --worker_in_master_cpus=48 \
    --lang="python" \
    --pythonpath=$(pwd) \
    test.py
```

## Exception
```
[ ERROR ]: An exception occurred: %sname 'compss_wain_on' is not defined
Traceback (most recent call last):
  File "/apps/COMPSs/3.3//Bindings/python/3/pycompss/runtime/launch.py", line 303, in compss_main
    compile(user_file.read(), app_path, "exec"), globals()
  File "test.py", line 15, in <module>
    res = compss_wain_on(res)
NameError: name 'compss_wain_on' is not defined
```

## Expected behaviour
That it prints both hello worlds in a `.out` file.

## Annex
- test.py (as givent to my by Jorge)
```
#!/usr/bin/python3
# -*- coding: utf-8 -*- 
from pycompss.api.api import compss_wait_on
from pycompss.api.task import task
from pycompss.api.parameter import *
@task()
def hello(name):
    return "Hello " + name
if __name__ == '__main__':
   res = hello("world")
   res = compss_wain_on(res)
   print(res)
```

**Comment by jorgee** [comment]
There is a typo. It should be compss_wait_on. In your code you have compss_wain_on.

**Comment by manuel-g-castro** [comment]
Well. That was an easy issue. Sorry!
